/** Represents the User data retrieved from the DB */
export interface User {
  userID?: number; // optional since it is auto-generated by the DB
  username: string;
  firstName: string;
  lastName: string;
  password: string;
  isAdmin: boolean;
}