/** Represents the User data retrieved from the DB */
export interface User {
  userID?: number; // optional since it is auto-generated by the DB
  username: string;
  firstName: string;
  lastName: string;
  password: string;
  isAdmin: number; // 0 = false. 1 = true. Need to convert this to boolean in JS logic
}