/** Represents the Ticket data retrieved from the DB */
export interface Ticket {
  ticketID?: number; // optional since it is auto-generated by the DB
  userID: number;
  title: string;
  description: string;
  priority: number;
  status: string;
  createdTime: string;
  updatedTime: string;
  username: string;

  // These fields will be popuplated from the server when joining with the users table
  firstName: string;
  lastName: string;
}

/** Ticket priority enum */
// Using numbers so we can sort data by priority
export enum Priority {
  High = 1,
  Medium = 2,
  Low = 3
}

/** Ticket status enum */
// Using strings so we can easily view the status from the DB.
// Not using numbers since there's no inherent sorting with statuses.
export enum Status {
  Open = "Open",
  InProgress = "In Progress",
  Resolved = "Resolved"
}